### ISSUE TITLE
можно добавить команду trnslate

### ISSUE THREAD

**Issue by Payziii** [oxenn/oxenedbot#1]

**Comment by oxened** [comment]
можно

**Comment by oxened** [comment]
разрешаю

**Comment by Payziii** [comment]
> разрешаю

могу затра пул реквест запилить

**Comment by oddyamill** [comment]
ну так добавляй сам раз такой молодец придумал супер пупер команду

**Comment by Payziii** [comment]
> ну так добавляй сам раз такой молодец придумал команду

ну так и добавлю

**Comment by oddyamill** [comment]
все жду

**Comment by FROGPEPE121** [comment]
завалите ебальники оболтусы

**Comment by sherrial** [comment]
че вы

**Comment by sherrial** [comment]
```javascript
a
```

**Comment by Payziii** [comment]
> че вы

все коммит закрыт

**Comment by Payziii** [comment]
не пиши сюда больше

**Comment by sherrial** [comment]
открыт

**Comment by sherrial** [comment]
моя проблема не решена

**Comment by oddyamill** [comment]
это не коммит

**Comment by sherrial** [comment]
К а к   в ы   о т н о с и т е с ь   к   О к с и м и р о н у ?

**Comment by Sherrixxx** [comment]
дебилы

**Comment by Sherrixxx** [comment]
> это не коммит

это пул реквест

**Comment by sherrial** [comment]
Э ЭТО НЕ Я
